// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xicjrygnmspbdrtyislq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpY2pyeWdubXNwYmRydHlpc2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODM4MzQsImV4cCI6MjA2ODE1OTgzNH0.VCr0AaxiffC-SL-l4QCmTlgm_8GCpSBuAHeVHWjxh1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});